version: 0.2

phases:
  build:
    commands:
      - echo Build Starting on `date`
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo $(basename ./build/libs/*.jar)
      - pwd
artifacts:
  files:
    - build/libs/*.jar
    - appspec.yml
    - scripts/**
  name: myname-$(date +%Y-%m-%d_%H:%M:%S)
  discard-paths: yes
cache:
  paths:
    - '/root/.gradle/caches/**/*'
